// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: builds.proto

package no.ion.mvndeps.proto;

public final class BuildsOuterClass {
  private BuildsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_no_ion_mvndeps_proto_Builds_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_no_ion_mvndeps_proto_Builds_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_no_ion_mvndeps_proto_Build_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_no_ion_mvndeps_proto_Build_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014builds.proto\022\024no.ion.mvndeps.proto\"5\n\006" +
      "Builds\022+\n\006builds\030\001 \003(\0132\033.no.ion.mvndeps." +
      "proto.Build\"R\n\005Build\022\017\n\007groupId\030\001 \001(\t\022\022\n" +
      "\nartifactId\030\002 \001(\t\022\014\n\004path\030\003 \001(\t\022\026\n\016build" +
      "TimeNanos\030\004 \001(\020B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_no_ion_mvndeps_proto_Builds_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_no_ion_mvndeps_proto_Builds_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_no_ion_mvndeps_proto_Builds_descriptor,
        new java.lang.String[] { "Builds", });
    internal_static_no_ion_mvndeps_proto_Build_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_no_ion_mvndeps_proto_Build_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_no_ion_mvndeps_proto_Build_descriptor,
        new java.lang.String[] { "GroupId", "ArtifactId", "Path", "BuildTimeNanos", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
