// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: builds.proto

package no.ion.mvndeps.proto;

public interface BuildsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:no.ion.mvndeps.proto.Builds)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
   */
  java.util.List<no.ion.mvndeps.proto.Build> 
      getBuildsList();
  /**
   * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
   */
  no.ion.mvndeps.proto.Build getBuilds(int index);
  /**
   * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
   */
  int getBuildsCount();
  /**
   * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
   */
  java.util.List<? extends no.ion.mvndeps.proto.BuildOrBuilder> 
      getBuildsOrBuilderList();
  /**
   * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
   */
  no.ion.mvndeps.proto.BuildOrBuilder getBuildsOrBuilder(
      int index);
}
