// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: builds.proto

package no.ion.mvndeps.proto;

/**
 * Protobuf type {@code no.ion.mvndeps.proto.Builds}
 */
public  final class Builds extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:no.ion.mvndeps.proto.Builds)
    BuildsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Builds.newBuilder() to construct.
  private Builds(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Builds() {
    builds_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Builds(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              builds_ = new java.util.ArrayList<no.ion.mvndeps.proto.Build>();
              mutable_bitField0_ |= 0x00000001;
            }
            builds_.add(
                input.readMessage(no.ion.mvndeps.proto.Build.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        builds_ = java.util.Collections.unmodifiableList(builds_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return no.ion.mvndeps.proto.BuildsOuterClass.internal_static_no_ion_mvndeps_proto_Builds_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return no.ion.mvndeps.proto.BuildsOuterClass.internal_static_no_ion_mvndeps_proto_Builds_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            no.ion.mvndeps.proto.Builds.class, no.ion.mvndeps.proto.Builds.Builder.class);
  }

  public static final int BUILDS_FIELD_NUMBER = 1;
  private java.util.List<no.ion.mvndeps.proto.Build> builds_;
  /**
   * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
   */
  public java.util.List<no.ion.mvndeps.proto.Build> getBuildsList() {
    return builds_;
  }
  /**
   * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
   */
  public java.util.List<? extends no.ion.mvndeps.proto.BuildOrBuilder> 
      getBuildsOrBuilderList() {
    return builds_;
  }
  /**
   * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
   */
  public int getBuildsCount() {
    return builds_.size();
  }
  /**
   * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
   */
  public no.ion.mvndeps.proto.Build getBuilds(int index) {
    return builds_.get(index);
  }
  /**
   * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
   */
  public no.ion.mvndeps.proto.BuildOrBuilder getBuildsOrBuilder(
      int index) {
    return builds_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < builds_.size(); i++) {
      output.writeMessage(1, builds_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < builds_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, builds_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof no.ion.mvndeps.proto.Builds)) {
      return super.equals(obj);
    }
    no.ion.mvndeps.proto.Builds other = (no.ion.mvndeps.proto.Builds) obj;

    boolean result = true;
    result = result && getBuildsList()
        .equals(other.getBuildsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBuildsCount() > 0) {
      hash = (37 * hash) + BUILDS_FIELD_NUMBER;
      hash = (53 * hash) + getBuildsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static no.ion.mvndeps.proto.Builds parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static no.ion.mvndeps.proto.Builds parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static no.ion.mvndeps.proto.Builds parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static no.ion.mvndeps.proto.Builds parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static no.ion.mvndeps.proto.Builds parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static no.ion.mvndeps.proto.Builds parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static no.ion.mvndeps.proto.Builds parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static no.ion.mvndeps.proto.Builds parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static no.ion.mvndeps.proto.Builds parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static no.ion.mvndeps.proto.Builds parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static no.ion.mvndeps.proto.Builds parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static no.ion.mvndeps.proto.Builds parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(no.ion.mvndeps.proto.Builds prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code no.ion.mvndeps.proto.Builds}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:no.ion.mvndeps.proto.Builds)
      no.ion.mvndeps.proto.BuildsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return no.ion.mvndeps.proto.BuildsOuterClass.internal_static_no_ion_mvndeps_proto_Builds_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return no.ion.mvndeps.proto.BuildsOuterClass.internal_static_no_ion_mvndeps_proto_Builds_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              no.ion.mvndeps.proto.Builds.class, no.ion.mvndeps.proto.Builds.Builder.class);
    }

    // Construct using no.ion.mvndeps.proto.Builds.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBuildsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (buildsBuilder_ == null) {
        builds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        buildsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return no.ion.mvndeps.proto.BuildsOuterClass.internal_static_no_ion_mvndeps_proto_Builds_descriptor;
    }

    @java.lang.Override
    public no.ion.mvndeps.proto.Builds getDefaultInstanceForType() {
      return no.ion.mvndeps.proto.Builds.getDefaultInstance();
    }

    @java.lang.Override
    public no.ion.mvndeps.proto.Builds build() {
      no.ion.mvndeps.proto.Builds result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public no.ion.mvndeps.proto.Builds buildPartial() {
      no.ion.mvndeps.proto.Builds result = new no.ion.mvndeps.proto.Builds(this);
      int from_bitField0_ = bitField0_;
      if (buildsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          builds_ = java.util.Collections.unmodifiableList(builds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.builds_ = builds_;
      } else {
        result.builds_ = buildsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof no.ion.mvndeps.proto.Builds) {
        return mergeFrom((no.ion.mvndeps.proto.Builds)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(no.ion.mvndeps.proto.Builds other) {
      if (other == no.ion.mvndeps.proto.Builds.getDefaultInstance()) return this;
      if (buildsBuilder_ == null) {
        if (!other.builds_.isEmpty()) {
          if (builds_.isEmpty()) {
            builds_ = other.builds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBuildsIsMutable();
            builds_.addAll(other.builds_);
          }
          onChanged();
        }
      } else {
        if (!other.builds_.isEmpty()) {
          if (buildsBuilder_.isEmpty()) {
            buildsBuilder_.dispose();
            buildsBuilder_ = null;
            builds_ = other.builds_;
            bitField0_ = (bitField0_ & ~0x00000001);
            buildsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBuildsFieldBuilder() : null;
          } else {
            buildsBuilder_.addAllMessages(other.builds_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      no.ion.mvndeps.proto.Builds parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (no.ion.mvndeps.proto.Builds) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<no.ion.mvndeps.proto.Build> builds_ =
      java.util.Collections.emptyList();
    private void ensureBuildsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        builds_ = new java.util.ArrayList<no.ion.mvndeps.proto.Build>(builds_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        no.ion.mvndeps.proto.Build, no.ion.mvndeps.proto.Build.Builder, no.ion.mvndeps.proto.BuildOrBuilder> buildsBuilder_;

    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public java.util.List<no.ion.mvndeps.proto.Build> getBuildsList() {
      if (buildsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(builds_);
      } else {
        return buildsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public int getBuildsCount() {
      if (buildsBuilder_ == null) {
        return builds_.size();
      } else {
        return buildsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public no.ion.mvndeps.proto.Build getBuilds(int index) {
      if (buildsBuilder_ == null) {
        return builds_.get(index);
      } else {
        return buildsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public Builder setBuilds(
        int index, no.ion.mvndeps.proto.Build value) {
      if (buildsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBuildsIsMutable();
        builds_.set(index, value);
        onChanged();
      } else {
        buildsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public Builder setBuilds(
        int index, no.ion.mvndeps.proto.Build.Builder builderForValue) {
      if (buildsBuilder_ == null) {
        ensureBuildsIsMutable();
        builds_.set(index, builderForValue.build());
        onChanged();
      } else {
        buildsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public Builder addBuilds(no.ion.mvndeps.proto.Build value) {
      if (buildsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBuildsIsMutable();
        builds_.add(value);
        onChanged();
      } else {
        buildsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public Builder addBuilds(
        int index, no.ion.mvndeps.proto.Build value) {
      if (buildsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBuildsIsMutable();
        builds_.add(index, value);
        onChanged();
      } else {
        buildsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public Builder addBuilds(
        no.ion.mvndeps.proto.Build.Builder builderForValue) {
      if (buildsBuilder_ == null) {
        ensureBuildsIsMutable();
        builds_.add(builderForValue.build());
        onChanged();
      } else {
        buildsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public Builder addBuilds(
        int index, no.ion.mvndeps.proto.Build.Builder builderForValue) {
      if (buildsBuilder_ == null) {
        ensureBuildsIsMutable();
        builds_.add(index, builderForValue.build());
        onChanged();
      } else {
        buildsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public Builder addAllBuilds(
        java.lang.Iterable<? extends no.ion.mvndeps.proto.Build> values) {
      if (buildsBuilder_ == null) {
        ensureBuildsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, builds_);
        onChanged();
      } else {
        buildsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public Builder clearBuilds() {
      if (buildsBuilder_ == null) {
        builds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        buildsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public Builder removeBuilds(int index) {
      if (buildsBuilder_ == null) {
        ensureBuildsIsMutable();
        builds_.remove(index);
        onChanged();
      } else {
        buildsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public no.ion.mvndeps.proto.Build.Builder getBuildsBuilder(
        int index) {
      return getBuildsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public no.ion.mvndeps.proto.BuildOrBuilder getBuildsOrBuilder(
        int index) {
      if (buildsBuilder_ == null) {
        return builds_.get(index);  } else {
        return buildsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public java.util.List<? extends no.ion.mvndeps.proto.BuildOrBuilder> 
         getBuildsOrBuilderList() {
      if (buildsBuilder_ != null) {
        return buildsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(builds_);
      }
    }
    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public no.ion.mvndeps.proto.Build.Builder addBuildsBuilder() {
      return getBuildsFieldBuilder().addBuilder(
          no.ion.mvndeps.proto.Build.getDefaultInstance());
    }
    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public no.ion.mvndeps.proto.Build.Builder addBuildsBuilder(
        int index) {
      return getBuildsFieldBuilder().addBuilder(
          index, no.ion.mvndeps.proto.Build.getDefaultInstance());
    }
    /**
     * <code>repeated .no.ion.mvndeps.proto.Build builds = 1;</code>
     */
    public java.util.List<no.ion.mvndeps.proto.Build.Builder> 
         getBuildsBuilderList() {
      return getBuildsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        no.ion.mvndeps.proto.Build, no.ion.mvndeps.proto.Build.Builder, no.ion.mvndeps.proto.BuildOrBuilder> 
        getBuildsFieldBuilder() {
      if (buildsBuilder_ == null) {
        buildsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            no.ion.mvndeps.proto.Build, no.ion.mvndeps.proto.Build.Builder, no.ion.mvndeps.proto.BuildOrBuilder>(
                builds_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        builds_ = null;
      }
      return buildsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:no.ion.mvndeps.proto.Builds)
  }

  // @@protoc_insertion_point(class_scope:no.ion.mvndeps.proto.Builds)
  private static final no.ion.mvndeps.proto.Builds DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new no.ion.mvndeps.proto.Builds();
  }

  public static no.ion.mvndeps.proto.Builds getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Builds>
      PARSER = new com.google.protobuf.AbstractParser<Builds>() {
    @java.lang.Override
    public Builds parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Builds(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Builds> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Builds> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public no.ion.mvndeps.proto.Builds getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

